version: 2
jobs:
  build:
    docker:
      - image: jigneshvasoya/gitlab:builder
    steps:
      - checkout
      - run:
          name: build
          command: ./build.sh
      - store_artifacts:
          path: build/cmake-hello_0.0.1-1_amd64.deb
          prefix: build
